// src/config/utilities.ts

export type UtilityCategory = 'developer' | 'text' | 'image' | 'calculator' | 'generator';

export interface UtilityConfig {
  id: string;
  title: string;
  description: string;
  category: UtilityCategory;
  isClientSideOnly: boolean;
  relatedUtilities: string[];
  status: 'live' | 'preview' | 'coming-soon';
  knowledgeId?: string;
}

export const UTILITIES: Record<string, UtilityConfig> = {
  'json-diff': {
    id: 'json-diff',
    title: 'JSON Diff & Compare',
    description: 'Compare two JSON documents structurally. Identify added, removed, and changed values instantly.',
    category: 'developer',
    isClientSideOnly: true,
    relatedUtilities: ['json-formatter', 'jwt-inspector', 'text-diff'],
    status: 'live',
    knowledgeId: 'json-diff',
  },
  'json-formatter': {
    id: 'json-formatter',
    title: 'JSON Formatter & Minifier',
    description: 'Beautify or compress your JSON data instantly. Format, validate, and minify JSON directly in your browser.',
    category: 'developer',
    isClientSideOnly: true,
    relatedUtilities: ['json-diff', 'url-parser', 'csv-json'],
    status: 'live',
    knowledgeId: 'json-formatter',
  },
  'jwt-inspector': {
    id: 'jwt-inspector',
    title: 'JWT Inspector',
    description: 'Inspect a JSON Web Token locally in your browser. Decode header, payload, and claims without sending data to any server.',
    category: 'developer',
    isClientSideOnly: true,
    relatedUtilities: ['base64', 'hash-generator'],
    status: 'live',
    knowledgeId: 'jwt-inspector',
  },
  'base64': {
    id: 'base64',
    title: 'Base64 Encoder & Decoder',
    description: 'Encode and decode text to Base64 or Base64URL instantly with full UTF-8 support. 100% client-side.',
    category: 'developer',
    isClientSideOnly: true,
    relatedUtilities: ['jwt-inspector', 'hash-generator', 'url-parser'],
    status: 'live',
    knowledgeId: 'base64',
  },
  'text-cleaner': {
    id: 'text-cleaner',
    title: 'Text Cleaner & Deduplicator',
    description: 'Remove duplicate lines, trim whitespace, and sort text lists instantly. Perfect for emails, URLs, and data cleanup.',
    category: 'text',
    isClientSideOnly: true,
    relatedUtilities: ['word-counter', 'text-case-converter', 'text-diff'],
    status: 'live',
    knowledgeId: 'text-cleaner',
  },
  'word-counter': {
    id: 'word-counter',
    title: 'Word & Character Counter',
    description: 'Analyze text instantly. Get accurate counts for characters, words, and lines directly in your browser.',
    category: 'text',
    isClientSideOnly: true,
    relatedUtilities: ['text-cleaner', 'text-case-converter'],
    status: 'live',
    knowledgeId: 'word-counter',
  },
  'image-resizer': {
    id: 'image-resizer',
    title: 'Image Resizer & Compressor',
    description: 'Resize and compress JPG, PNG, and WEBP images directly in your browser. No uploads, fast and private.',
    category: 'image',
    isClientSideOnly: true,
    relatedUtilities: ['image-format-converter', 'favicon-generator', 'image-metadata'],
    status: 'live',
    knowledgeId: 'image-resizer',
  },
  'qr-code-generator': {
    id: 'qr-code-generator',
    title: 'QR Code Generator',
    description: 'Generate a high-quality QR code from any text or URL instantly. 100% client-side, no data leaves your browser.',
    category: 'generator',
    isClientSideOnly: true,
    relatedUtilities: ['secure-random-generator', 'url-parser'],
    status: 'live',
    knowledgeId: 'qr-code-generator',
  },
  'color-converter': {
    id: 'color-converter',
    title: 'Color Converter',
    description: 'Convert colors between HEX, RGB, and HSL formats instantly. 100% client-side.',
    category: 'developer',
    isClientSideOnly: true,
    relatedUtilities: ['color-contrast'],
    status: 'live',
    knowledgeId: 'color-converter',
  },
  'unit-converter': {
    id: 'unit-converter',
    title: 'Unit Converter',
    description: 'Convert common length and weight units instantly. Your measurements are processed locally in your browser.',
    category: 'calculator',
    isClientSideOnly: true,
    relatedUtilities: ['base-number-converter', 'time-difference'],
    status: 'live',
    knowledgeId: 'unit-converter',
  },
  'timestamp-converter': {
    id: 'timestamp-converter',
    title: 'Epoch / Unix Timestamp Converter',
    description: 'Convert between Unix timestamps and human-readable dates. Your inputs are processed locally in your browser.',
    category: 'developer',
    isClientSideOnly: true,
    relatedUtilities: ['json-formatter', 'jwt-inspector', 'time-difference'],
    status: 'live',
    knowledgeId: 'timestamp-converter',
  },
  'secure-random-generator': {
    id: 'secure-random-generator',
    title: 'Secure Random Generator',
    description: 'Generate cryptographically secure random values using your browser Web Crypto API. Values are generated locally and not stored.',
    category: 'generator',
    isClientSideOnly: true,
    relatedUtilities: ['qr-code-generator', 'hash-generator', 'password-generator', 'uuid-generator'],
    status: 'live',
    knowledgeId: 'secure-random-generator',
  },
  'image-format-converter': {
    id: 'image-format-converter',
    title: 'Image Format Converter',
    description: 'Convert images between JPEG, PNG, and WEBP formats instantly. All processing happens locally in your browser.',
    category: 'image',
    isClientSideOnly: true,
    relatedUtilities: ['image-resizer', 'favicon-generator', 'image-metadata'],
    status: 'live',
    knowledgeId: 'image-format-converter',
  },
  'text-case-converter': {
    id: 'text-case-converter',
    title: 'Text Case & Naming Converter',
    description: 'Instantly convert text between camelCase, snake_case, kebab-case, and other programming naming conventions. 100% client-side.',
    category: 'text',
    isClientSideOnly: true,
    relatedUtilities: ['text-cleaner', 'word-counter'],
    status: 'live',
    knowledgeId: 'text-case-converter',
  },
  'base-number-converter': {
    id: 'base-number-converter',
    title: 'Base Number Converter',
    description: 'Convert integers between Binary, Octal, Decimal, and Hexadecimal instantly. Supports arbitrary-precision integers. 100% client-side.',
    category: 'calculator',
    isClientSideOnly: true,
    relatedUtilities: ['unit-converter'],
    status: 'live',
    knowledgeId: 'base-number-converter',
  },
  'hash-generator': {
    id: 'hash-generator',
    title: 'Hash Generator',
    description: 'Generate SHA-256 and SHA-512 cryptographic hashes from text instantly. UTF-8 encoded, 100% client-side using Web Crypto API.',
    category: 'developer',
    isClientSideOnly: true,
    relatedUtilities: ['base64', 'jwt-inspector', 'secure-random-generator', 'uuid-generator'],
    status: 'live',
    knowledgeId: 'hash-generator',
  },
  'url-parser': {
    id: 'url-parser',
    title: 'URL Parser & Query Tool',
    description: 'Parse, inspect, and manipulate URL structures and query parameters instantly. 100% client-side, no network requests.',
    category: 'developer',
    isClientSideOnly: true,
    relatedUtilities: ['base64', 'json-formatter', 'qr-code-generator'],
    status: 'live',
    knowledgeId: 'url-parser',
  },
  'password-generator': {
    id: 'password-generator',
    title: 'Password Generator',
    description: 'Generate cryptographically secure, unbiased passwords entirely in your browser. No storage, no transmission.',
    category: 'generator',
    isClientSideOnly: true,
    relatedUtilities: ['secure-random-generator', 'hash-generator', 'uuid-generator'],
    status: 'live',
    knowledgeId: 'password-generator',
  },
  'uuid-generator': {
    id: 'uuid-generator',
    title: 'UUID Generator',
    description: 'Generate standard UUID v4 and v7 identifiers locally in your browser. RFC 9562 compliant, no storage, no transmission.',
    category: 'generator',
    isClientSideOnly: true,
    relatedUtilities: ['secure-random-generator', 'password-generator', 'hash-generator'],
    status: 'live',
    knowledgeId: 'uuid-generator',
  },
  'favicon-generator': {
    id: 'favicon-generator',
    title: 'Favicon & App Icon Generator',
    description: 'Generate standard favicon and app icon sizes from any image. All processing happens locally in your browser.',
    category: 'image',
    isClientSideOnly: true,
    relatedUtilities: ['image-resizer', 'image-format-converter', 'image-metadata'],
    status: 'live',
    knowledgeId: 'favicon-generator',
  },
  'time-difference': {
    id: 'time-difference',
    title: 'Time Difference Calculator',
    description: 'Calculate the elapsed time between two instants in ISO 8601 format. All processing happens locally in your browser.',
    category: 'calculator',
    isClientSideOnly: true,
    relatedUtilities: ['timestamp-converter', 'unit-converter'],
    status: 'live',
    knowledgeId: 'time-difference',
  },
  'text-diff': {
    id: 'text-diff',
    title: 'Plain Text Diff & Compare',
    description: 'Compare two blocks of text line-by-line to find additions, deletions, and changes. 100% client-side.',
    category: 'developer',
    isClientSideOnly: true,
    relatedUtilities: ['json-diff', 'text-cleaner'],
    status: 'live',
    knowledgeId: 'text-diff',
  },
  'csv-json': {
    id: 'csv-json',
    title: 'CSV ↔ JSON Converter',
    description: 'Convert CSV data to JSON and vice versa with strict RFC 4180-style validation. 100% client-side.',
    category: 'developer',
    isClientSideOnly: true,
    relatedUtilities: ['json-formatter', 'text-cleaner'],
    status: 'live',
    knowledgeId: 'csv-json',
  },
  'image-metadata': {
    id: 'image-metadata',
    title: 'Image Metadata Inspector',
    description: 'Inspect EXIF and metadata from your images locally. Understand what information your photos carry before sharing them.',
    category: 'image',
    isClientSideOnly: true,
    relatedUtilities: ['image-resizer', 'image-format-converter', 'favicon-generator'],
    status: 'live',
    knowledgeId: 'image-metadata',
  },
  'color-contrast': {
    id: 'color-contrast',
    title: 'Color Contrast Checker',
    description: 'Calculate the contrast ratio between two colors and verify WCAG 2.x accessibility compliance. 100% client-side.',
    category: 'developer',
    isClientSideOnly: true,
    relatedUtilities: ['color-converter'],
    status: 'live',
    knowledgeId: 'color-contrast',
  },
};

export function getUtility(id: string): UtilityConfig | undefined {
  return UTILITIES[id];
}

export function getUtilitiesByCategory(category: UtilityCategory): UtilityConfig[] {
  return Object.values(UTILITIES).filter((u) => u.category === category);
}